name: Cypress Tests

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
       # Make sure you put workflow kit action on top of all the steps
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: 0aeb9c19-c17f-4bfb-956b-bd7fd3e8f05e

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.4
        with:
          start: npm run start-with-coverage
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.CYPRESS_GITHUB_TOKEN }}

      - name: Compile LCOV report
        run: npm run cover:report

       # Make sure you put test kit action after your test execution step
      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: 0aeb9c19-c17f-4bfb-956b-bd7fd3e8f05e
          test_format: JUNIT
          test_framework: CYPRESS
          test_path: ./cypress-junit-results.xml
          coverage_format: LCOV/TXT
          coverage_path: ./coverage/lcov.info
