# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Jest and generate coverage

on:
  push:
    branches:
      - master

jobs:
  run-jest-and-generate-coverage:
    runs-on: ubuntu-latest

    steps:
    # Make sure you put workflow kit action on top of all the steps
    - name: Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: 0aeb9c19-c17f-4bfb-956b-bd7fd3e8f05e

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run Jest
      run: npm run test-and-cover

    # Make sure you put test kit action after your test execution step
    - name: Analyze Test and/or Coverage Results
      uses: runforesight/foresight-test-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: 0aeb9c19-c17f-4bfb-956b-bd7fd3e8f05e
        test_format: JUNIT
        test_framework: JEST
        test_path: ./jest-junit-results.xml
        coverage_format: LCOV/TXT
        coverage_path: ./coverage/lcov.info

    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: master
