# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Jest and generate coverage

on:
  push:
    branches:
      - master

jobs:
  run-jest-and-generate-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run Jest
      run: npm run test-and-cover

    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: master
