# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Jest and generate coverage

on:
  push:
    branches:
      - master

jobs:
  run-jest-and-generate-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run Jest
      run: npm run test-and-cover

    - name: Jest Coverage Comment
      id: coverageComment
      uses: MishaKav/jest-coverage-comment@main

    - name: Create the badge
      if: github.ref == 'refs/heads/master'
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
        gistID: 9971936c552d17eb9f2141f03733c586
        filename: mx-io-test.json
        label: Coverage
        message: ${{ steps.coverageComment.outputs.coverage }}%
        color: ${{ steps.coverageComment.outputs.color }}
        namedLogo: jest

    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: master
