# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run All Tests and Generate Code Coverage

on:
  push:
    branches:
      - master

jobs:
  run-tests-and-generate-coverage:
    runs-on: ubuntu-latest

    steps:
    # Make sure you put workflow kit action on top of all the steps
    - name: Collect Workflow Telemetry
      uses: runforesight/foresight-workflow-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: 0aeb9c19-c17f-4bfb-956b-bd7fd3e8f05e

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Code Climate Setup
      uses: amancevice/setup-code-climate@v1
      with:
        cc_test_reporter_id: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}

    - name: Code Climate Before Build
      run: cc-test-reporter before-build

    - name: Run Jest
      run: npm run test-and-cover

    - name: Code Climate Format Coverge
      run: cc-test-reporter format-coverage ./coverage/jest/lcov.info --input-type lcov --output ./coverage/jest/cc-jest.json

    - name: Run Cypress
      uses: cypress-io/github-action@v5.0.4
      with:
        start: npm run start-with-coverage
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # pass GitHub token to allow accurately detecting a build vs a re-run build
        GITHUB_TOKEN: ${{ secrets.CYPRESS_GITHUB_TOKEN }}

    - name: Code Climate Format Coverge
      run: cc-test-reporter format-coverage ./coverage/cypress/lcov.info --input-type lcov --output ./coverage/cypress/cc-cypress.json

    - name: Code Climate Sum Coverage
      run: cc-test-reporter sum-coverage coverage/**/cc-*.json --parts 2

    - name: Code Climate Upload Coverage
      run: cc-test-reporter upload-coverage

    - name: Compile LCOV report
      run: npm run cover:report

    - name: Combine LCOV reports
      run: npm run cover:combine

    - name: Combine JUNIT reports
      run: npm run combine-junit-reports



    # Make sure you put test kit action after your test execution step
    - name: Analyze Test and/or Coverage Results
      uses: runforesight/foresight-test-kit-action@v1
      if: ${{ always() }}
      with:
        api_key: 0aeb9c19-c17f-4bfb-956b-bd7fd3e8f05e
        test_format: JUNIT
        test_framework: JUNIT
        test_path: ./combined-junit-results.xml
        coverage_format: LCOV/TXT
        coverage_path: ./coverage/combined-lcov.info

    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: master
